[appearance]
font_name = "JetBrains Mono"
scale_factor = 1.1




[[CustomModule]]
name = "CursorPos"
command = "/home/sean/.local/bin/ashell-cursorpos"
# Optional, but allowed: you can still include this for clarity
listen_cmd = "/home/sean/.local/bin/ashell-cursorpos"


[modules]
left = [ "Workspaces", "CursorPos"]
center = [ "Clock" ]
right = ["MediaPlayer", "SystemInfo", [ "Privacy", "Settings" ]] 




[clock]
format = "%D %I:%M %p"

[system_info]
indicators = [ "Cpu", "Memory", { Disk = "/home" } , "DownloadSpeed", "UploadSpeed", "Temperature" ]

[system_info.cpu]
warn_threshold = 60
alert_threshold = 80

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.disk]
warn_threshold = 80
alert_threshold = 90

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80

[media_player]
max_title_length = 50
